version: "3.2"
services:
  kafka:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - published: ${ZOOKEEPER_PORT}
        target: 2181
      - published: ${KAFKA_PORT}
        target: 9092
    hostname: ${KAFKA_HOSTNAME}
